stages:

  prepare:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
      - data/raw/UCI_Credit_Card.csv
    outs:
      - data/processed/credit_data_processed.csv

  features:
    cmd: python src/features/build_features.py
    deps:
      - src/features/build_features.py
      - data/processed/credit_data_processed.csv
    outs:
      - data/processed/credit_data_features.csv

  train:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/credit_data_features.csv
    outs:
      - models/best_model.joblib
      - models/model_metrics.json
