stages:
  features:
    cmd: python src/features/build_features.py
    deps:
    - data/processed/credit_data_processed.csv
    - src/features/build_features.py
    outs:
    - data/processed/credit_data_features.csv
  prepare:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw/UCI_Credit_Card.csv
    - src/data/make_dataset.py
    outs:
    - data/processed/credit_data_processed.csv
